---
title: "Normalization and Statistical Analysis"
author: "Christian Ayala"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

This Notebook is to perform normalization of the area under the curve (AUC) of the peaks detected by *Compound Discoverer*.

# 1. Importing Libraries

```{r libraries, message=FALSE}
library(NormalyzerDE)
library(tidyverse)
library(readxl)
library(ggpubr)
library(ggsci)
library(gtools)
source('functions_cdis_norm_stats.R')
```

# 2. Import data

The input data is the **compounds-table** generated by the previous scripts

```{r set_path, message=FALSE}
# set path variables
project_dir <- getwd()
project_name <- 'Bog_labeled_1.7int'
figures_dir <- file.path(project_dir, paste0(project_name, '_output_figures'))
tables_dir <- file.path(project_dir,  paste0(project_name, '_output_tables'))
compounds_table_file <- file.path(tables_dir, 'compounds_table.csv')

# Load compounds_table

compounds_table <- read_csv(compounds_table_file)

# Import metadata and fix names
metadata_file <- file.path(tables_dir, 'fixed_metadata.csv')
metadata <- read_csv(metadata_file)

```

# 3. Data Manipulation and Transformation

```{r Data_manipulation}
# Create a new tibble with the AUC per each mass from each sample
auc_table <- compounds_table %>% 
  select(FeatureID, SampleID, AUC)

# Transform the dataframe into a matrix-like table

auc_table <-  spread(auc_table, SampleID, AUC)
auc_table$FeatureID <- factor(auc_table$FeatureID, levels = str_sort(auc_table$FeatureID, numeric = TRUE))
auc_table <- auc_table %>% 
  arrange(FeatureID)


# Save untransformed data

table_file <- file.path(tables_dir, 'untransformed_auc_table.tsv')
write_tsv(auc_table, table_file)

# Log-transform the data

auc_table <- log10(auc_table + 1)

# Save the transformed data

table_file <- file.path(tables_dir, 'transformed_auc_table.tsv')
write_tsv(auc_table, table_file)
```

# 4. Data Normalization by multiple methods

```{r Data_normalization}




```



```{r NormalyzerDE}

# Create grouping column in the metadata

metadata <- metadata %>% 
  mutate(Group = paste(Label, Time, sep = '.'))

write_tsv(file = file.path(tables_dir, 'group_metadata.tsv'), metadata)
metadata_file <- file.path(tables_dir, 'group_metadata.tsv')

  

desing_table <- tibble(sample = compounds_table$SampleID)
auc_file <- file.path(tables_dir, 'untransformed_auc_table.tsv')

normalyzer(jobName = 'label_test_run', 
           designPath = metadata_file, 
           dataPath = auc_file, 
           outputDir = tables_dir,
           sampleColName = 'SampleID',
           groupColName = 'Group',
           requireReplicates = FALSE)

```



