---
title: "Data import - Metabotandem"
author: "Christian Ayala"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# 1. Importing libraries

Make sure `xcms` is installed.

```{r}
library(xcms)
doParallel::registerDoParallel(10)
```

# 2. Import data

**Important** Data was already in centroid mode.

```{r}

#set path variables
project_dir <- getwd()

# Give a name for your project so the results are all grouped together in a directory with the same name
project_name <- 'Bog_1e5_gap_filter'
figures_dir <- file.path(project_dir, paste0(project_name, '_output_figures'))
tables_dir <- file.path(project_dir,  paste0(project_name, '_output_tables'))

mzML_file <- file.path(project_dir, 'data', 'Bog_unlbl_1e5_export.mzML')

# Read the data:
data_cent <- readMSData(mzML_file, 
                        mode = "onDisk",
                        verbose = TRUE)
```

The MS experiment is now represented as an `OnDiskMSnExp` object. 

Information stored in the `OnDiskMSnExp` object after import:
```{r}
show(data_cent)
```

Check if data is centroided:

```{r}
prelim <- fData(data_cent)[1:100,]
unique(fData(data_cent)$centroided)
```

# 3. Save R object as `.RData`

Save as an R object so later, you don't need to re-import the data
```{r}
## Save data object as rds

save_file <- file.path(tables_dir, 'mzMLData.R')

save(data_cent, file = save_file)
```

